# Generated by Django 4.0.4 on 2022-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='scolarship_type',
            field=models.ManyToManyField(to='main.scholarship'),
        ),
        migrations.AddField(
            model_name='student',
            name='applications',
            field=models.ManyToManyField(to='main.application'),
        ),
    ]
