# Generated by Django 4.0.4 on 2022-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_scolarship_type_application_scholarship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='scholarship_type',
            field=models.ManyToManyField(blank=True, null=True, to='main.scholarship'),
        ),
    ]
