# Generated by Django 4.0.4 on 2022-05-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_application_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='scholarship_type',
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.scholarship'),
        ),
    ]
