# Generated by Django 4.0.4 on 2022-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_application_scholarship_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='money',
            field=models.IntegerField(default=2300),
            preserve_default=False,
        ),
    ]
