# Generated by Django 4.0.4 on 2022-05-06 17:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_scholarship_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_field',
            field=ckeditor.fields.RichTextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.CharField(max_length=255),
        ),
    ]
